### ISSUE TITLE
Seems to be your api key? If yes, you should remove it

### ISSUE THREAD

**Issue by impnguyen** [maninywa/temperature-with-nest-and-typescript#3]
https://github.com/maninywa/temperature-with-nest-and-typescript/blob/1c352b41bed807e682d60f8ad5164a5a0dce48cf/_postman/nestjs-temperature-service.postman_collection.json#L80

**Comment by waznico** [comment]
This is an internal id created by postman. An api key is not set there. It's only configured within api-key.ts (described in readme).
